### ISSUE TITLE
No Favicon

### ISSUE THREAD

**Issue by rbkoffee** [redbrick/techweek.dcu.ie#3]
Need the Redbrick favicon for the TechWeek or a new TechWeek one.

**Comment by SeanHealy33** [comment]
I'd be in favor of using a tech week specific one.

**Comment by rbkoffee** [comment]
@SeanHealy33 
http://www.redbrick.dcu.ie/~koffee/uploads/favicon.ico

**Comment by rbkoffee** [comment]
Favicon integrated into Live Site.

**Comment by rbkoffee** [comment]
Merged & Issue closed <3
