### ISSUE TITLE
move to sass

### ISSUE THREAD

**Issue by butlerx** [redbrick/techweek.dcu.ie#33]
despite having just moved to less id like to move us to sass
if we did we could add materialize as  a dep and import its sass into the build process

**Comment by clementallen** [comment]
@butlerx I'm happy to do this

**Comment by butlerx** [comment]
good luck

**Comment by clementallen** [comment]
@butlerx just for clarification would you like it in sass or scss syntax?

**Comment by butlerx** [comment]
sorry scss

**Comment by clementallen** [comment]
@butlerx good, that's my preferred one :)
