### ISSUE TITLE
use # to link to specific event 

### ISSUE THREAD

**Issue by butlerx** [redbrick/techweek.dcu.ie#37]
use a url tag to link to a specific event

**Comment by aj07** [comment]
@butlerx which link you are talking about?

**Comment by butlerx** [comment]
@aj07 im saying use a tag in the url to link to specific days or talks
for sharing of events

**Comment by DeMuu** [comment]
I started with giving the possibility to "link" to specific days using URL hash. #45 
Guess this is expandable to specific talks

**Comment by butlerx** [comment]
done in #45
