### ISSUE TITLE
Pull Request Etiquette 

### ISSUE THREAD

**Issue by SeanHealy33** [redbrick/techweek.dcu.ie#39]
There is no point having a PR based system if you're just going to abuse your admin privilege when it people request changes. The review exists for a reason...

@butlerx @GoldenBadger @VoyTechnology

**Comment by butlerx** [comment]
its not an abuse of admin privileges its an exercise of the need for them. 
They are there for when a pr gets blocked. 
The changes had been made

**Comment by redbrickCmt** [comment]
Closing issue. 
Reason: Not an actual issue with site. HTTP301
