### ISSUE TITLE
Fonts not loaded

### ISSUE THREAD

**Issue by DeMuu** [redbrick/techweek.dcu.ie#43]
![screen shot 2016-10-05 at 10 39 22](https://cloud.githubusercontent.com/assets/19406963/19106546/2f98ff96-8ae8-11e6-9678-7d24b00e24f8.png)

**Comment by c4d3r** [comment]
https://github.com/redbrick/techweek.dcu.ie/pull/46

**Comment by butlerx** [comment]
clo
