### ISSUE TITLE
minimize html

### ISSUE THREAD

**Issue by butlerx** [redbrick/techweek.dcu.ie#54]

**Comment by afranco20** [comment]
exactly which files do you want minimized?

**Comment by butlerx** [comment]
theres 3 index.html file one in the root dir and the others in 2015 and 2016 these are the files to be minimized and outputted to the dist file with their event.json in the same dir

**Comment by butlerx** [comment]
theres also comments at the top of the page you'll need to remove

**Comment by shivamluthra** [comment]
@butlerx Hi sir,
i actually wanted to contribute to this repo and cloned it to my machine yesterday. I was having problems while setup process as the terminal showed me some errors while npm install command execution. Moreover, i wasn't able to run gulp command to run index.html file at localhost. Can you please guide me ?

**Comment by butlerx** [comment]
what where your errors with the `npm install`

**Comment by shivamluthra** [comment]
@butlerx i sorted it out . now it's working ! Can you assign me for this issue ? And what else is to be minimised in index.html apart from removing comments at top? 
Thanks.

**Comment by butlerx** [comment]
removing the whitespace and comments should be everything 

i also can assign you the issue as you arnt part of the repo or the organisation

**Comment by kartik95** [comment]
Is this issue resolved? @butlerx

**Comment by butlerx** [comment]
this issue isnt resolved but @shivamluthra only said he was goign to work on it yesterday

**Comment by shivamluthra** [comment]
@butlerx I am done with the minification part. Just remind me again that do i have to place all three index.html files along with their event.json in dist directory only or let them be there in different folders only as it is there before?

**Comment by butlerx** [comment]
put them in the dist directory with the event beside them but they need to keep their folder structure so you should have `./dist/index.html`, `./dist/event.json`, and `./dist/2015`, `./dist/2016` with theire index and event.json in them
