### ISSUE TITLE
Replace Video Stream in 2015 archive with Youtube Playlist. 

### ISSUE THREAD

**Issue by rbkoffee** [redbrick/techweek.dcu.ie#9]
Replace: 
src="//media.heanet.ie/player/live.php?streamGUID=31c30c43d755240b5559eac4323c57c9&amp;StreamType="

With
src="https://www.youtube.com/embed/videoseries?list=PLPaLJSHTDMFgYNnnEOjuvdm6WqOFTSQ9z" 

in the id="live"

**Comment by rbkoffee** [comment]
Done

**Comment by SeanHealy33** [comment]
can you submit a PR for that change?

**Comment by rbkoffee** [comment]
Do you want me to create a feature branch for the 2015 site as it's logically a separate entity from the current site?

**Comment by SeanHealy33** [comment]
I can see that it works so if you want to just push direct you can do that too :)

**Comment by rbkoffee** [comment]
Not going to create a branch for it at the moment. 
We'll look into how we manage site revs.
